In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split, GridSearchCV


# generate two class dataset
data = pd.read_csv("test-15.csv")
data.tail()

In C:\Users\93513\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\Users\93513\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\Users\93513\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.


No  IS  Age  NeuP  NeuC  MonP  LymP  Hgb  RDW-CV    MCV  MCHC   UA  \
2091    7839   0   54  44.9  2.21   3.2  49.0  135    13.6  100.0   314  190   
2092  306237   1   77  75.3  5.34   3.8  17.0  130    13.6   94.0   327  304   
2093  436103   1   48  54.9  5.37   6.0  36.5  151    13.0   94.6   342  420   
2094  387125   1   70  81.5  6.77   5.4  12.4  128    12.5   99.0   328  562   
2095   14514   0   62  55.1  2.82   4.4  37.3  161    14.7   97.0   324  283   

        CG  AKP    TP    TC  HDL-C  
2091  26.6   75  70.1  5.45   1.86  
2092  21.4   70  61.2  4.00   0.78  
2093  22.3   64  62.8  6.06   1.09  
2094  25.1   83  73.2  5.87   1.25  
2095  31.3   80  73.7  4.38   1.26

In [2]:
data=data.drop(['No'],axis=1)
# Split target and features
X = data.drop(['IS'],axis=1)
X
y = data['IS']
y = y.astype(int)
y
print(X.shape)
print(y.shape)

(2096, 15)
(2096,)


In [3]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
X_features = X
sc = StandardScaler()
X = sc.fit_transform(X)

In [4]:
# internal validation - ML models in testing dataset
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.linear_model import ElasticNet
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB



# logistic regression
model1 = LogisticRegression(C=1.01)
# knn
model2 = KNeighborsClassifier(n_neighbors=31)
# RF
model3 = RandomForestClassifier(random_state=25,criterion='entropy',n_estimators=187)

# XGBoost
model4 = XGBClassifier(learning_rate=0.01, n_estimators=1000, silent=0, gamma=0.2, subsample=0.75, 
                       objective='binary:logistic', reg_alpha=1, reg_lambda=1,seed=27,
                      max_depth=5, min_child_weight=6)

## elastic net
##model5 = ElasticNet(alpha=0.001, l1_ratio=0.1)

# neural network
model6 = MLPClassifier(alpha=0.001, hidden_layer_sizes=17)

# GaussianNB
model7=GaussianNB() ##因为唯一参数 var_smoothing设置为非默认值时， evaluation metrics的值很不理想

## 所以此处直接就是 by default 来设置

C:\Users\93513\Anaconda3\lib\site-packages\dask\dataframe\utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [5]:
# fit model
model1.fit(X, y)
model2.fit(X, y)
model3.fit(X, y)
model4.fit(X, y)
## model5.fit(X_train, y_train)
model6.fit(X, y)
model7.fit(X, y)

# predict probabilities
pred_prob1 = model1.predict_proba(X)
pred_prob2 = model2.predict_proba(X)
pred_prob3 = model3.predict_proba(X)
pred_prob4 = model4.predict_proba(X)
## pred_prob5 = model5.predict(X_test)
pred_prob6 = model6.predict_proba(X)
pred_prob7 = model7.predict_proba(X)

[10:37:55] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.2.0\src\learner.cc:516: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




C:\Users\93513\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:585: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [6]:
pred1 = model1.predict(X)
pred2 = model2.predict(X)
pred3 = model3.predict(X)
pred4 = model4.predict(X)
## pred5 = model5.predict(X_test)
pred6 = model6.predict(X)
pred7 = model7.predict(X)

In [7]:
print(pred1)
print(pred2)
print(pred3)

[1 0 0 ... 1 1 0]
[0 0 0 ... 0 1 0]
[1 0 1 ... 1 1 0]


In [8]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score, roc_curve

# roc curve for models
fpr1, tpr1, thresh1 = roc_curve(y, pred_prob1[:,1], pos_label=1)
fpr2, tpr2, thresh2 = roc_curve(y, pred_prob2[:,1], pos_label=1)
fpr3, tpr3, thresh3 = roc_curve(y, pred_prob3[:,1], pos_label=1)
fpr4, tpr4, thresh4 = roc_curve(y, pred_prob4[:,1], pos_label=1)
## fpr5, tpr5, thresh5 = roc_curve(y_test, pred_prob5, pos_label=1)
fpr6, tpr6, thresh6 = roc_curve(y, pred_prob6[:,1], pos_label=1)
fpr7, tpr7, thresh7 = roc_curve(y, pred_prob7[:,1], pos_label=1)

# roc curve for tpr = fpr 
random_probs = [0 for i in range(len(y))]
p_fpr, p_tpr, _ = roc_curve(y, random_probs, pos_label=1)

# pos_label : 整数或者字符串, 默认None，表示被认为是正类样本的类别, 可以不填，因为运行三五十个点后就可以看到ROC曲线了

In [9]:
# AUC score can be computed using the roc_auc_score() method of sklearn:


### 因为 elastic net的很多evaluation metrics 不能显示，所以接下来注掉 model5

from sklearn.metrics import roc_auc_score


In [10]:
def bootstrap_auc(model1, X, y, nsamples=1000):
    auc_values1 = []
    for b in range(nsamples):
        idx1 = np.random.randint(X.shape[0], size=X.shape[0])
        model1.fit(X[idx1], y[idx1])
        pred1_ = model1.predict_proba(X)[:, 1]
        roc_auc1 = roc_auc_score(y.ravel(), pred1_.ravel())
        auc_values1.append(roc_auc1)
    return np.percentile(auc_values1, (2.5, 97.5))

In [11]:
# 1 - auc scores testing set
auc_score1 = roc_auc_score(y, pred_prob1[:,1])
auc_score2 = roc_auc_score(y, pred_prob2[:,1])
auc_score3 = roc_auc_score(y, pred_prob3[:,1])
auc_score4 = roc_auc_score(y, pred_prob4[:,1])
## auc_score5 = roc_auc_score(y_test, pred_prob5)
auc_score6 = roc_auc_score(y, pred_prob6[:,1])
auc_score7 = roc_auc_score(y, pred_prob7[:,1])



print(auc_score1, auc_score2, auc_score3, auc_score4,auc_score6,auc_score7)

0.8979247071229131 0.9129742519924214 1.0 0.9812675422953464 0.9294714210524875 0.8822197633996454


In [12]:
## Calculating 95% CI for AUC

#### https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.stack.imgur.com%2FzFGNa.png&imgrefurl=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F50437354%2Fhow-to-calculate-95-confidence-interval-for-auc-from-confusion-matrix&tbnid=vFftbLzgp01LlM&vet=12ahUKEwintYqzxozzAhUTUn0KHQfoDFkQMygAegUIARCqAQ..i&docid=jK-T-QoSUo5GyM&w=1622&h=836&q=calculating%20confidence%20interval%20auc%20python&ved=2ahUKEwintYqzxozzAhUTUn0KHQfoDFkQMygAegUIARCqAQ


### https://gist.github.com/doraneko94/e24643136cfb8baf03ef8a314ab9615c

In [13]:
acc1 = model1.score(X,y)
acc2 = model2.score(X,y)
acc3 = model3.score(X,y)
acc4 = model4.score(X,y)
## acc5 = model5.score(X_train,y_train)
acc6 = model6.score(X,y)
acc7 = model7.score(X,y)
print(acc1,acc2,acc3,acc4,acc6,acc7)

0.8187022900763359 0.8206106870229007 1.0 0.9265267175572519 0.8587786259541985 0.8086832061068703


In [14]:
import warnings
import pandas
from sklearn import model_selection
from sklearn.metrics import log_loss
from sklearn.metrics import precision_recall_fscore_support as score, precision_score, recall_score, f1_score

warnings.filterwarnings('ignore')

In [15]:
# 3-precision
precision1 = precision_score(y, pred1)
precision2 = precision_score(y, pred2)
precision3 = precision_score(y, pred3)
precision4 = precision_score(y, pred4)
## precision5 = precision_score(y_test, pred5)
precision6 = precision_score(y, pred6)
precision7 = precision_score(y, pred7)
print(precision1,precision2,precision3,precision4,precision6,precision7)

0.8282402528977871 0.8865598027127004 1.0 0.9318413021363174 0.8709338929695698 0.8382022471910112
